### ISSUE TITLE
Crash with various mods

### ISSUE THREAD

**Issue by brisingraerowing** [Lathanael/FacadePainter#4]
[Crash Log](https://paste.dimdev.org/ziqafefobe.mccrash)

It seems you're passing negative numbers to the metadata functions (or EIO base is).

**Comment by Lathanael** [comment]
Interesting. Have you tried if the same happens with Ender IO as well (without my mod that is)? I am asking because to me it looks like that particular crash should still happen if not it must be a loading time issue. Will look into it.

**Comment by brisingraerowing** [comment]
I'll test it.

**Comment by brisingraerowing** [comment]
It works with just Ender IO.

EDIT: It seems to be another mod breaking something, as it works in a testing instance with just Ender IO. I'll look into this further.

**Comment by Lathanael** [comment]
Nah it seems like it is something i am doing or a combination of what GalaticCraft does and i do not account for.

**Comment by Lathanael** [comment]
Oh wow that is weird! The issue is with how Galacticraft references to its own blocks:

[return values()[meta - 3];](https://github.com/micdoodle8/Galacticraft/blob/671a70a779869bfa119d4c2b6f036d9c5653fbf5/src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockBasic.java#L70)

Now i need to find out why it works out for Ender IO but crashes for me. That'll be interesting -.-

**Comment by brisingraerowing** [comment]
I also got the crash with [BlockDetector](https://minecraft.curseforge.com/projects/blockdetector).

**Comment by Lathanael** [comment]
Meaning BlockDetector and Galacticraft crashed or BD and my mod crashed? If later please include the crash log here as well

**Comment by brisingraerowing** [comment]
BD and this mod. I'll try and find the log again.

**Comment by brisingraerowing** [comment]
[Here you go](https://paste.dimdev.org/acariyehax.mccrash)

**Comment by Lathanael** [comment]
Can you please try the following build?
[https://transfer.sh/lxEPW/FacadePainter-beta.jar](https://transfer.sh/lxEPW/FacadePainter-beta.jar)

It should fix the Galacticraft crash. The BD I can not reproduce with just BD and FP. ~~Does it crash on load?~~ Well dumb me for not looking at the complete log, yes it does...

**Comment by brisingraerowing** [comment]
It no longer crashes on startup, but VanillaFix pops up a message on world load about a crash in a scheduled task.

[Here's the error for that](https://paste.dimdev.org/puqajofefo.mccrash)

**Comment by Lathanael** [comment]
This build should no longer crash.

[https://transfer.sh/sFs4M/FacadePainter-beta2.jar](https://transfer.sh/sFs4M/FacadePainter-beta2.jar)

**Comment by brisingraerowing** [comment]
I'll test that when I get a chance.

**Comment by brisingraerowing** [comment]
Forgot to reply after testing. It works perfectly fine now.

**Comment by Lathanael** [comment]
Thanks :)
